ARG BASE_IMAGE=381491823703.dkr.ecr.us-east-1.amazonaws.com/gz-harmonic-headless:gz-harmonic.px4-02103b9100.7fedb94
FROM ${BASE_IMAGE}

COPY simulation-worlds ${FIRMWARE_DIR}/Tools/simulation/gz/worlds/custom
COPY simulation-models ${FIRMWARE_DIR}/Tools/simulation/gz/models/custom
COPY simulation-plugins ${FIRMWARE_DIR}/build/src/modules/simulation/gz_plugins

COPY edit_rcS.bash ${WORKSPACE_DIR}/
COPY sim_speed_controller.py ${WORKSPACE_DIR}/
COPY respawn_watchdog.sh ${WORKSPACE_DIR}/
COPY entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh

ENTRYPOINT ["/root/entrypoint.sh"]
